name: dropdown_button2
description: Flutter's core Dropdown Button widget with steady dropdown menu and many options you can customize to your needs.
version: 1.5.3
homepage: https://github.com/AhmedLSayed9/dropdown_button2

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0